---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
    - 9d0dc93056b702111c70ef3adbc8bcc7412458e434ea8349ed76852d15ca32f8
    - d2c2c86ebf22542853ed0137047d94682f628b3501e3fe8b5b750911104aeb91
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/
- vendor/
- tools/
- "app/assets/javascripts/bootstrap-colorpicker.js"
- "app/controllers/dev/pdf_controller.rb"

