language: ruby
before_install:
  - sudo apt-get install libxslt-dev libxml2-dev
  - gem install bundler
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/application.yml{.example,}
  - cp config/database.yml{.example,}
  - bundle exec rake db:setup
script: bundle exec rspec --format documentation
rvm:
  - 2.1.1
branches:
  only:
    - master
    - production
notifications:
  campfire: collectiveidea:3c3f07431323f476b2fa69acb37c040ebe7f8f36@109379
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
env:
  - CODECLIMATE_REPO_TOKEN=d6c14655ddff198718ea2c98a73973c24ff1b9d812d06b822aa85018ebef547d CAPYBARA_WAIT_TIME=30
cache: bundler
services:
  - memcached
addons:
  hosts:
    - localtest.me
