insert into phrases (pcat_id, label, tags, default_value, sort_order, edit_type, info_note) values (3, 'error:customer:minimum_error', NULL, 'You have not met the minimum order requirement of {1}.', 1, 'text', NULL);
insert into phrases (pcat_id, label, tags, default_value, sort_order, edit_type, info_note) values (8, 'email:order_mm_notification', NULL, '<table width=\"100%\"> 		<colgroup><col width=\"1%\"> 		<col width=\"1%\"> 		<col width=\"98%\"> 		</colgroup><tbody><tr> 			<td>{logo}</td> 			<td>&nbsp;&nbsp;</td> 			<td> 				<h2>LO #: {order_nbr}</h2> 			</td> 		</tr> 	</tbody></table> 	<br>&nbsp;<br> 	You\'ve received a new order!<br>You can check the details of this and all your current orders by logging into your {hubname} account. <br>&nbsp;<br>	 	{items}  	<br><br>If you have any questions please respond to this email.<br>', 20, 'rte', ' You have the following fields available: {fullname}, {order_nbr}, {items}, {payment_type}, {payment_confirm_code}, {hubname}, {logo}');

update phrases set pcat_id = 1, label = 'button:save_and_continue', tags = NULL, default_value = 'save & continue editing', sort_order = 3, edit_type = 'text', info_note  = NULL where phrase_id = 3;
update phrases set pcat_id = 1, label = 'button:save_and_go_back', tags = NULL, default_value = 'save & go back', sort_order = 4, edit_type = 'text', info_note  = NULL where phrase_id = 4;
update phrases set pcat_id = 1, label = 'button:login', tags = 'customer', default_value = 'log in', sort_order = 9, edit_type = 'text', info_note  = NULL where phrase_id = 9;
update phrases set pcat_id = 2, label = 'header:reg:spamprotection', tags = 'customer', default_value = 'Let us know you\'re not a robot!', sort_order = 15, edit_type = 'text', info_note  = NULL where phrase_id = 15;
update phrases set pcat_id = 4, label = 'field:customer:email', tags = 'customer', default_value = 'Email Address', sort_order = 33, edit_type = 'text', info_note  = NULL where phrase_id = 33;
update phrases set pcat_id = 4, label = 'field:customer:email-match', tags = 'customer', default_value = 'Retype Email Address', sort_order = 34, edit_type = 'text', info_note  = NULL where phrase_id = 34;
update phrases set pcat_id = 6, label = 'nav2:emails:tests', tags = NULL, default_value = 'Email Testing', sort_order = 78, edit_type = 'text', info_note  = NULL where phrase_id = 78;
update phrases set pcat_id = 5, label = 'organizations:facebook', tags = NULL, default_value = 'Facebook (coming soon)', sort_order = 1, edit_type = 'text', info_note  = NULL where phrase_id = 117;
update phrases set pcat_id = 5, label = 'organizations:twitter', tags = NULL, default_value = 'Twitter (coming soon)', sort_order = 1, edit_type = 'text', info_note  = NULL where phrase_id = 118;
update phrases set pcat_id = 5, label = 'hub:features:sellers_enter_price_without_fees', tags = NULL, default_value = 'If you turn this feature on, then the edit price tab on producst will show the price of a product MINUS the market fees of the seller\'s home market. When the price is saved, the fees are added back in', sort_order = 1, edit_type = 'textarea', info_note  = NULL where phrase_id = 162;

