/*
SELECT table_name, CONCAT('DROP TABLE IF EXISTS ',table_name,';') ,
       CONCAT(ROUND(table_rows / 1,0), '')                                    rows,
       CONCAT(ROUND(data_length / ( 1024), 2), 'K')                    DATA,
       CONCAT(ROUND(index_length / ( 1024), 2), 'K')                   idx,
       CONCAT(ROUND(( data_length + index_length ) / ( 1024 * 1024 ), 3), 'K') total_size,
FROM   information_schema.TABLES
WHERE table_schema = 'localorb_www_dev'
ORDER  BY table_name
LIMIT  1000;
*/



ALTER TABLE domains_branding   MODIFY is_temp tinyint;
ALTER TABLE organizations  MODIFY payment_entity_id int(10) UNSIGNED DEFAULT '0';
  
  
  
  
  
DROP IF TABLE EXISTS account_types;
DROP IF TABLE EXISTS admin_role;
DROP IF TABLE EXISTS admin_rule;
DROP IF TABLE EXISTS admin_user;
DROP IF TABLE EXISTS adminnotification_inbox;

DROP IF TABLE EXISTS api_role;
DROP IF TABLE EXISTS api_rule;
DROP IF TABLE EXISTS api_session;
DROP IF TABLE EXISTS api_user;

DROP IF TABLE EXISTS catalog_category_entity_int;
DROP IF TABLE EXISTS catalog_category_entity_text;
DROP IF TABLE EXISTS catalog_category_entity_varchar;
DROP IF TABLE EXISTS catalog_category_entity;
DROP IF TABLE EXISTS catalog_category_flat_store_1;
DROP IF TABLE EXISTS catalog_category_flat_store_10;
DROP IF TABLE EXISTS catalog_category_flat_store_2;
DROP IF TABLE EXISTS catalog_category_flat_store_3;
DROP IF TABLE EXISTS catalog_category_flat_store_4;
DROP IF TABLE EXISTS catalog_category_flat_store_5;
DROP IF TABLE EXISTS catalog_category_flat_store_6;
DROP IF TABLE EXISTS catalog_category_flat_store_7;
DROP IF TABLE EXISTS catalog_category_flat_store_8;
DROP IF TABLE EXISTS catalog_category_flat_store_9;
DROP IF TABLE EXISTS catalog_category_flat;
DROP IF TABLE EXISTS catalog_category_product_index;
DROP IF TABLE EXISTS catalog_category_product;
DROP IF TABLE EXISTS catalog_compare_item;
DROP IF TABLE EXISTS catalog_product_enabled_index;
DROP IF TABLE EXISTS catalog_product_entity_decimal;
DROP IF TABLE EXISTS catalog_product_entity_int;
DROP IF TABLE EXISTS catalog_product_entity_media_gallery_value;
DROP IF TABLE EXISTS catalog_product_entity_media_gallery;
DROP IF TABLE EXISTS catalog_product_entity_text;
DROP IF TABLE EXISTS catalog_product_entity_tier_price;
DROP IF TABLE EXISTS catalog_product_entity_varchar;
DROP IF TABLE EXISTS catalog_product_entity;
DROP IF TABLE EXISTS catalog_product_flat_10;
DROP IF TABLE EXISTS catalog_product_flat_11;
DROP IF TABLE EXISTS catalog_product_flat_4;
DROP IF TABLE EXISTS catalog_product_flat_5;
DROP IF TABLE EXISTS catalog_product_flat_6;
DROP IF TABLE EXISTS catalog_product_flat_7;
DROP IF TABLE EXISTS catalog_product_flat_8;
DROP IF TABLE EXISTS catalog_product_flat_9;
DROP IF TABLE EXISTS catalog_product_link_attribute;
DROP IF TABLE EXISTS catalog_product_link_type;
DROP IF TABLE EXISTS catalog_product_website;
DROP IF TABLE EXISTS catalogindex_aggregation_tag;
DROP IF TABLE EXISTS catalogindex_aggregation_to_tag;
DROP IF TABLE EXISTS catalogindex_eav;
DROP IF TABLE EXISTS catalogindex_minimal_price;
DROP IF TABLE EXISTS catalogindex_price;
DROP IF TABLE EXISTS cataloginventory_stock_item;
DROP IF TABLE EXISTS cataloginventory_stock_status;
DROP IF TABLE EXISTS cataloginventory_stock;
DROP IF TABLE EXISTS catalogrule_product_price;
DROP IF TABLE EXISTS catalogrule_product;
DROP IF TABLE EXISTS catalogrule;
DROP IF TABLE EXISTS catalogsearch_fulltext;
DROP IF TABLE EXISTS catalogsearch_query;
DROP IF TABLE EXISTS cms_block_store;
DROP IF TABLE EXISTS cms_block;
DROP IF TABLE EXISTS cms_page_store;
DROP IF TABLE EXISTS cms_page;
DROP IF TABLE EXISTS core_config_data;
DROP IF TABLE EXISTS core_email_template;
DROP IF TABLE EXISTS core_flag;
DROP IF TABLE EXISTS core_resource;
DROP IF TABLE EXISTS core_store_group;
DROP IF TABLE EXISTS core_store;
DROP IF TABLE EXISTS core_translate;
DROP IF TABLE EXISTS core_url_rewrite;
DROP IF TABLE EXISTS core_website;
DROP IF TABLE EXISTS cron_schedule;
DROP IF TABLE EXISTS customer_address_entity_int;
DROP IF TABLE EXISTS customer_address_entity_text;
DROP IF TABLE EXISTS customer_address_entity_varchar;
DROP IF TABLE EXISTS customer_address_entity;
DROP IF TABLE EXISTS customer_entity_text;
DROP IF TABLE EXISTS customer_group;
DROP IF TABLE EXISTS dataflow_profile;
DROP IF TABLE EXISTS design_change;
DROP IF TABLE EXISTS directory_currency_rate;
DROP IF TABLE EXISTS Discount;
DROP IF TABLE EXISTS eav_attribute_group;
DROP IF TABLE EXISTS eav_attribute_option_value;
DROP IF TABLE EXISTS eav_attribute_option;
DROP IF TABLE EXISTS eav_attribute_set;
DROP IF TABLE EXISTS eav_attribute;
DROP IF TABLE EXISTS eav_entity_attribute;
DROP IF TABLE EXISTS eav_entity_store;
DROP IF TABLE EXISTS eav_entity_type;
DROP IF TABLE EXISTS entity;
DROP IF TABLE EXISTS FAQ;
DROP IF TABLE EXISTS id_table;
DROP IF TABLE EXISTS inventory;
DROP IF TABLE EXISTS invite;
DROP IF TABLE EXISTS LatestNews;
DROP IF TABLE EXISTS lo_cron_run;
DROP IF TABLE EXISTS lo_order_modifiers;
DROP IF TABLE EXISTS lo_quote_modifiers;
DROP IF TABLE EXISTS log_quote;
DROP IF TABLE EXISTS log_summary_type;
DROP IF TABLE EXISTS log_url_info;
DROP IF TABLE EXISTS log_url;
DROP IF TABLE EXISTS log_visitor_info;
DROP IF TABLE EXISTS log_visitor;
DROP IF TABLE EXISTS minimumquantity;
DROP IF TABLE EXISTS modifier_types;
DROP IF TABLE EXISTS newsletter_subscriber;
DROP IF TABLE EXISTS newsletter_template;
DROP IF TABLE EXISTS o2m_category;
DROP IF TABLE EXISTS o2m_customer;
DROP IF TABLE EXISTS o2m_order;
DROP IF TABLE EXISTS o2m_product;
DROP IF TABLE EXISTS o2m_vendor;
DROP IF TABLE EXISTS orbitadmin;
DROP IF TABLE EXISTS orbitbuyer;
DROP IF TABLE EXISTS orbitpermission;
DROP IF TABLE EXISTS orbitrole;
DROP IF TABLE EXISTS orbitvendor;
DROP IF TABLE EXISTS orders;
DROP IF TABLE EXISTS paymentsorders;
DROP IF TABLE EXISTS paypal_api_debug;
DROP IF TABLE EXISTS photos;
DROP IF TABLE EXISTS poll_answer;
DROP IF TABLE EXISTS poll_store;
DROP IF TABLE EXISTS poll;
DROP IF TABLE EXISTS postits;
DROP IF TABLE EXISTS price;
DROP IF TABLE EXISTS product_alert_price;
DROP IF TABLE EXISTS product;
DROP IF TABLE EXISTS quantity;
DROP IF TABLE EXISTS rating_entity;
DROP IF TABLE EXISTS rating_option;
DROP IF TABLE EXISTS rating;
DROP IF TABLE EXISTS report_event_types;
DROP IF TABLE EXISTS report_event;
DROP IF TABLE EXISTS review_detail;
DROP IF TABLE EXISTS review_entity_summary;
DROP IF TABLE EXISTS review_entity;
DROP IF TABLE EXISTS review_status;
DROP IF TABLE EXISTS review_store;
DROP IF TABLE EXISTS review;
DROP IF TABLE EXISTS rewards_currency;
DROP IF TABLE EXISTS rewards_special;
DROP IF TABLE EXISTS rewards_transfer_reference;
DROP IF TABLE EXISTS rewards_transfer;
DROP IF TABLE EXISTS sales_flat_order_item;
DROP IF TABLE EXISTS sales_flat_quote_address;
DROP IF TABLE EXISTS sales_flat_quote_item_option;
DROP IF TABLE EXISTS sales_flat_quote_item;
DROP IF TABLE EXISTS sales_flat_quote_payment;
DROP IF TABLE EXISTS sales_flat_quote_shipping_rate;
DROP IF TABLE EXISTS sales_flat_quote;
DROP IF TABLE EXISTS sales_order_datetime;
DROP IF TABLE EXISTS sales_order_decimal;
DROP IF TABLE EXISTS sales_order_entity_datetime;
DROP IF TABLE EXISTS sales_order_entity_decimal;
DROP IF TABLE EXISTS sales_order_entity_int;
DROP IF TABLE EXISTS sales_order_entity_text;
DROP IF TABLE EXISTS sales_order_entity_varchar;
DROP IF TABLE EXISTS sales_order_entity;
DROP IF TABLE EXISTS sales_order_int;
DROP IF TABLE EXISTS sales_order_text;
DROP IF TABLE EXISTS sales_order_varchar;
DROP IF TABLE EXISTS sales_order;
DROP IF TABLE EXISTS salesrule;
DROP IF TABLE EXISTS sendfriend_log;
DROP IF TABLE EXISTS shipping_tablerate;
DROP IF TABLE EXISTS sitemap;
DROP IF TABLE EXISTS statuses;
DROP IF TABLE EXISTS systemsetting;
DROP IF TABLE EXISTS tag_relation;
DROP IF TABLE EXISTS tag_summary;
DROP IF TABLE EXISTS tag;
DROP IF TABLE EXISTS tax_calculation_rate_title;
DROP IF TABLE EXISTS tax_calculation_rate;
DROP IF TABLE EXISTS tax_calculation_rule;
DROP IF TABLE EXISTS tax_calculation;
DROP IF TABLE EXISTS tax_class;
DROP IF TABLE EXISTS taxonomy;
DROP IF TABLE EXISTS transaction_types;
DROP IF TABLE EXISTS transactions;
DROP IF TABLE EXISTS updateemaillist;
DROP IF TABLE EXISTS vendorcatalog;
DROP IF TABLE EXISTS version;
DROP IF TABLE EXISTS wishlist;