# Machine generated with some manual tweaks to support initial
# Chef's Warehouse import while Eric was thinking about how to
# map categories.
#
# select quote_ident(child.name)||' => '||
#        child.id||','||' # '||parent.name
# from categories child, categories parent
# where child.parent_id=parent.id and
#       parent.id in (select id from categories
#                     where parent_id=1244)
# order by child.name, parent.name;

module ProductImport
  CategoryMap = {
    "Almond Butter" => 1369, # Prepared Foods
    "Annual" => 1231, # Membership
    "Apple Butter" => 760, # Prepared Foods
    "Apples" => 361, # Fruits
    "Applesauce" => 761, # Prepared Foods
    "Art" => 1196, # Art, Crafts & Pottery
    "Artichokes, Asparagus, & Avocados" => 1161, # Vegetables
    "Bagels" => 69, # Breads & Baked Goods
    "Baking Mixes" => 308, # Flours & Baking Needs
    "Baking Needs" => 1529, # Flours & Baking Needs
    "Bananas" => 360, # Fruits
    "Barley" => 740, # Pasta, Rice, Grains & Dried Beans
    "Beans" => 732, # Pasta, Rice, Grains & Dried Beans
    "Beans & Peas" => 1143, # Vegetables
    "Bedding" => 1213, # Household
    "Beef Testicles" => 1405, # Meat & Poultry
    "Beer, Wine, & Spirits" => 17, # Beverages
    "Beet Greens" => 984, # Vegetables
    "Berries & Cherries" => 344, # Fruits
    "Beverages" => 1507, # Beverages
    "Biscotti" => 77, # Breads & Baked Goods
    "Bottles" => 1267, # Bottle
    "Braising Mix" => 983, # Vegetables
    "Bread & Rolls" => 36, # Breads & Baked Goods
    "Bread Flour" => 307, # Flours & Baking Needs
    "Breads & Baked Goods" => 1500, # Breads & Baked Goods
    "Broccoli, Cauliflower & Cabbage" => 1129, # Vegetables
    "Brownies" => 104, # Breads & Baked Goods
    "Buckwheat Flour" => 1435, # Flours & Baking Needs
    "Burritos" => 1442, # Prepared Foods
    "Butter" => 206, # Dairy, Cheese & Eggs
    "CSA Share" => 1437, # Membership
    "Canned Seafood" => 1531, # Fish & Seafood
    "Carrots & Celery" => 1121, # Vegetables
    "Casserole" => 823, # Prepared Foods
    "Cat Food" => 1485, # Pet Products
    "Cereal" => 1288, # Breakfast
    "Cheese" => 162, # Dairy, Cheese & Eggs
    "Cheese Blintz" => 106, # Breads & Baked Goods
    "Chili Powder" => 833, # Spices & Seasonings
    "Chilies" => 1534, # Spices & Seasonings
    "Chingers" => 114, # Chocolate & Sweets
    "Chips" => 1226, # Snacks
    "Chocolate" => 1530, # Chocolate & Sweets
    "Chocolate & Sweets" => 1514, # Chocolate & Sweets
    "Chocolate Truffles" => 117, # Chocolate & Sweets
    "Chocolate, Dark" => 115, # Chocolate & Sweets
    "Cider & Juice" => 7, # Beverages
    "Citrus" => 337, # Fruits
    "Cleaning Products" => 1215, # Household
    "Clothing" => 1509, # Clothing
    "Cobblers" => 107, # Breads & Baked Goods
    "Coffee, Tea, & Cocoa" => 14, # Beverages
    "Condiments" => 1533, # Condiments, Sauces & Sweeteners
    "Condiments, Sauces & Sweeteners" => 1513, # Condiments, Sauces & Sweeteners
    "Cookbook" => 1222, # Cookbooks
    "Cookies & Cakes" => 27, # Breads & Baked Goods
    "Corn" => 1115, # Vegetables
    "Corn Meal" => 306, # Flours & Baking Needs
    "Crackers" => 67, # Breads & Baked Goods
    "Crafts" => 1195, # Art, Crafts & Pottery
    "Crepes" => 1441, # Prepared Foods
    "Crumbles" => 108, # Breads & Baked Goods
    "Cucumbers, Squash & Pumpkins" => 1074, # Vegetables
    "Cured Meats" => 389, # Meat & Poultry
    "Dairy, Cheese & Eggs" => 1508, # Dairy, Cheese & Eggs
    "Dips & Spreads" => 774, # Prepared Foods
    "Donuts" => 105, # Breads & Baked Goods
    "Dried Apples" => 220, # Dried Fruits, Nuts & Seeds
    "Dried Apricots" => 219, # Dried Fruits, Nuts & Seeds
    "Dried Blueberries" => 218, # Dried Fruits, Nuts & Seeds
    "Dried Cranberries" => 217, # Dried Fruits, Nuts & Seeds
    "Dried Figs" => 216, # Dried Fruits, Nuts & Seeds
    "Dried Fruits" => 1518, # Dried Fruits, Nuts & Seeds
    "Dried Herbs" => 834, # Spices & Seasonings
    "Dried Peaches" => 1324, # Dried Fruits, Nuts & Seeds
    "Dried Persimmons" => 1313, # Dried Fruits, Nuts & Seeds
    "Dried Sweet Cherries" => 215, # Dried Fruits, Nuts & Seeds
    "Dried Tart Cherries" => 214, # Dried Fruits, Nuts & Seeds
    "Edibles" => 1186, # Flowers & Plants
    "Eggplants, Peppers & Okra" => 1034, # Vegetables
    "Eggs" => 151, # Dairy, Cheese & Eggs
    "Energy Bars" => 1452, # Snacks
    "Exfoliants" => 1198, # Health & Beauty
    "Fats" => 498, # Meat & Poultry
    "Fermented Raw Foods" => 794, # Prepared Foods
    "Fermented Soy Products" => 1477, # Prepared Foods
    "Fertilizer" => 1240, # Agriculture Supplies
    "Figs" => 1279, # Fruits
    "Fish & Seafood" => 1510, # Fish & Seafood
    "Flatbreads" => 97, # Breads & Baked Goods
    "Flours" => 1535, # Flours & Baking Needs
    "Flours & Baking Needs" => 1501, # Flours & Baking Needs
    "Fresh" => 248, # Fish & Seafood
    "Fresh" => 397, # Meat & Poultry
    "Fresh Herbs" => 985, # Vegetables
    "Fresh or Dried Arrangements" => 1172, # Flowers & Plants
    "Frozen" => 228, # Fish & Seafood
    "Frozen" => 1270, # Fruits
    "Frozen" => 504, # Meat & Poultry
    "Frozen" => 1280, # Prepared Foods
    "Frozen" => 1269, # Vegetables
    "Fruits" => 1504, # Fruits
    "Fudge" => 1271, # Chocolate & Sweets
    "Gardening Guides/Manuals" => 1241, # Agriculture Supplies
    "Gift Cards" => 1273, # Gift Cards
    "Grain" => 1239, # Agriculture Supplies
    "Grains" => 1387, # Pasta, Rice, Grains & Dried Beans
    "Grains" => 1283, # Pasta, Rice, Grains & Dried Beans
    "Granola" => 66, # Breads & Baked Goods
    "Granola" => 112, # Breakfast
    "Grapes" => 331, # Fruits
    "Grill Rub Seasoning" => 825, # Spices & Seasonings
    "Hay" => 1237, # Agriculture Supplies
    "Healthcare" => 1526, # Healthcare
    "Herb Mix" => 830, # Spices & Seasonings
    "Herbal Remedies" => 1209, # Health & Beauty
    "Honey" => 129, # Condiments, Sauces & Sweeteners
    "Honey, Raw" => 131, # Condiments, Sauces & Sweeteners
    "Hops" => 1490, # Flowers & Plants
    "Ice Cream" => 116, # Chocolate & Sweets
    "Ice Cream" => 209, # Dairy, Cheese & Eggs
    "Jams & Jellies" => 781, # Prepared Foods
    "Jarred" => 1389, # Prepared Foods
    "Kefir" => 208, # Dairy, Cheese & Eggs
    "Labneh" => 207, # Dairy, Cheese & Eggs
    "Leafy Greens" => 940, # Vegetables
    "Lentils" => 1296, # Pasta, Rice, Grains & Dried Beans
    "Lettuce & Salad Greens" => 962, # Vegetables
    "Lifetime" => 1232, # Membership
    "Live" => 276, # Fish & Seafood
    "Lotions & Salves" => 1205, # Health & Beauty
    "Manure" => 1236, # Agriculture Supplies
    "Maple Cream" => 1323, # Condiments, Sauces & Sweeteners
    "Mayonnaise" => 1516, # Condiments, Sauces & Sweeteners
    "Meat & Poultry" => 1505, # Meat & Poultry
    "Melons" => 324, # Fruits
    "Microgreens" => 1282, # Vegetables
    "Miscellaneous" => 1538,
    "Milk & Cream" => 141, # Dairy, Cheese & Eggs
    "Millet" => 731, # Pasta, Rice, Grains & Dried Beans
    "Monthly" => 1230, # Membership
    "Muesli" => 111, # Breakfast
    "Muffins & Scones" => 62, # Breads & Baked Goods
    "Mushrooms" => 931, # Vegetables
    "Mustard" => 1336, # Condiments, Sauces & Sweeteners
    "Nut Butters" => 1515, # Prepared Foods
    "Nuts" => 221, # Dried Fruits, Nuts & Seeds
    "Oats" => 729, # Pasta, Rice, Grains & Dried Beans
    "Oils" => 688, # Oils & Vinegars
    "Onions & Garlic" => 923, # Vegetables
    "Ornamental Shrubs" => 1171, # Flowers & Plants
    "Packaging & Supplies" => 1525, # Packaging & Supplies
    "Packaging Supplies" => 1292, # Agriculture Supplies
    "Pad Thai" => 1444, # Prepared Foods
    "Pancake Mix" => 110, # Breakfast
    "Pasta" => 708, # Pasta, Rice, Grains & Dried Beans
    "Pasta, Rice, Grains & Dried Beans" => 1511, # Pasta, Rice, Grains & Dried Beans
    "Pastries" => 25, # Breads & Baked Goods
    "Pastry Flour" => 305, # Flours & Baking Needs
    "Peaches" => 385, # Fruits
    "Peanut Butter" => 816, # Prepared Foods
    "Pears" => 323, # Fruits
    "Perennials" => 1167, # Flowers & Plants
    "Pesto" => 799, # Prepared Foods
    "Pet Treats" => 1217, # Pet Products
    "Pickles & Relishes" => 762, # Prepared Foods
    "Pierogi" => 819, # Prepared Foods
    "Pies" => 85, # Breads & Baked Goods
    "Polenta" => 707, # Pasta, Rice, Grains & Dried Beans
    "Popcorn" => 1225, # Snacks
    "Portion Packs" => 1528, # Portion Packs
    "Potato Pancakes" => 820, # Prepared Foods
    "Potatoes & Root Vegetables" => 882, # Vegetables
    "Pottery" => 1194, # Art, Crafts & Pottery
    "Prepared Foods" => 1503, # Prepared Foods
    "Prepared Foods" => 822, # Prepared Foods
    "Pretzels" => 1224, # Snacks
    "Produce Boxes" => 1499, # Agriculture Supplies
    "Prunes" => 213, # Dried Fruits, Nuts & Seeds
    "Quiche" => 818, # Prepared Foods
    "Quick Breads" => 1272, # Breads & Baked Goods
    "Quince" => 386, # Fruits
    "Quinoa" => 704, # Pasta, Rice, Grains & Dried Beans
    "Rabbits" => 1243, # Livestock
    "Raisins, Black" => 212, # Dried Fruits, Nuts & Seeds
    "Raisins, Golden" => 211, # Dried Fruits, Nuts & Seeds
    "Rhubarb" => 384, # Fruits
    "Rice" => 698, # Pasta, Rice, Grains & Dried Beans
    "Rice Milk" => 6, # Beverages
    "Rye Flour" => 304, # Flours & Baking Needs
    "Salad Dressing" => 130, # Condiments, Sauces & Sweeteners
    "Salads" => 817, # Prepared Foods
    "Salsa" => 806, # Prepared Foods
    "Sauces" => 125, # Condiments, Sauces & Sweeteners
    "Sauces" => 753, # Prepared Foods
    "Sea Salts" => 832, # Spices & Seasonings
    "Seasonal" => 1349, # Membership
    "Seeds" => 1256, # Dried Fruits, Nuts & Seeds
    "Sesame Seeds" => 1429, # Spices & Seasonings
    "Smoked Meats" => 1287, # Meat & Poultry
    "Snacks" => 1502, # Snacks
    "Soap" => 1201, # Health & Beauty
    "Soups" => 743, # Prepared Foods
    "Soy Milk" => 5, # Beverages
    "Specialty" => 2, # Beverages
    "Specialty Eggs" => 202, # Dairy, Cheese & Eggs
    "Specialty Flour" => 303, # Flours & Baking Needs
    "Specialty Products" => 1527, # Specialty Products
    "Specialty Vegetables" => 866, # Vegetables
    "Spelt Flour" => 1380, # Flours & Baking Needs
    "Spices & Seasonings" => 1517, # Spices & Seasonings
    "Split Peas" => 1297, # Pasta, Rice, Grains & Dried Beans
    "Sprouts" => 1281, # Vegetables
    "Stew" => 1443, # Prepared Foods
    "Stocks & Bases" => 754, # Prepared Foods
    "Stone Fruit" => 316, # Fruits
    "Straw" => 1238, # Agriculture Supplies
    "Strawberries" => 383, # Fruits
    "Stuffed Bread" => 821, # Prepared Foods
    "Sugar" => 121, # Condiments, Sauces & Sweeteners
    "Syrup" => 119, # Condiments, Sauces & Sweeteners
    "T-Shirt" => 1234, # Clothing
    "Tamales" => 1440, # Prepared Foods
    "Tomatoes" => 847, # Vegetables
    "Tortillas" => 99, # Breads & Baked Goods
    "Trail Mix" => 803, # Prepared Foods
    "Tropical & Specialty" => 312, # Fruits
    "Vegetables" => 1506, # Vegetables
    "Vinegars" => 679, # Oils & Vinegars
    "Water" => 1496, # Beverages
    "Weekly" => 1348, # Membership
    "Wheat Berries" => 741, # Pasta, Rice, Grains & Dried Beans
    "Wheat Free" => 1275, # Breads & Baked Goods
    "Wheat-Free Baked Goods" => 74, # Breads & Baked Goods
    "Whey" => 205, # Dairy, Cheese & Eggs
    "White Flour" => 310, # Flours & Baking Needs
    "Whole Wheat Flour" => 309, # Flours & Baking Needs
    "Wild Nettles" => 1185, # Flowers & Plants
    "Wild Perennials" => 1374, # Flowers & Plants
    "Yogurt" => 133, # Dairy, Cheese & Eggs
  }
end
