update phrase_categories set name='Titles' where pcat_id=7;
insert into phrase_categories (name,sort_order) values ('E-mails',8);
alter table phrases modify column default_value text;
alter table phrases add edit_type ENUM('text', 'textarea', 'rte');
alter table phrases add info_note text;

insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:simple_test','<h1>{testname}</h1><h2>this is a subheader</h2>this is a test. <a href="http://{hostname}/#!auth-form">Login</a>','You have the following fields available: {testname}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:reg_invite','<h1>Join LocalOrbit today!</h1>You have been invited to join LocalOrbit by a member of your company. To complete your registration, click <a href="{link}">this link</a>','You have the following fields available: {link}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:new_registrant','<h1>almost there!</h1>Dear {first_name},<br />&nbsp;<br />Thank you for registering with Local Orbit, your online ordering service for local food.<br />&nbsp;<br />To activate your account, please click on the following link:<br /><a href="{link}">{link}</a>.<br />&nbsp;<br />If clicking on the link does not work, copy and paste URL above into a new browser window.','You have the following fields available: {first_name}, {link}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:reg_mm_notification','<h1>hooray, a new user!</h1>A new user has registered on your hub! Their contact info is below:<br />&nbsp;<br />Company: {company}<br />Name: {fullname}<br />Email: {email}<br /><br />&nbsp;<br />If you would like to activate this organization, <a href="{activate}">click Here</a>','You have the following fields available: {company}, {fullname}, {email}, {activate}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:buyer_welcome','<h1>Welcome!</h1>Dear {first_name},<br /><h3>Ordering fresh food from local farmers just got easier!</h3><h4>All-in-One Ordering</h4>Ordering is simple. Farmers post their inventory on Local Orbit. You place your order and pay online. Farmers deliver to your business address, located at {delivery_address}.<br />&nbsp;<br />If you have any questions, please reply to this email or call Customer Service at 734-418-8628.<br />&nbsp;<br /><h4>Our Commitment</h4>Local Orbit will be available to you by phone, text (734-931-0393), email and online to provide support. We rarely sleep and will respond quickly to issues as they come up. If there is a problem with your account, your payments or anything else, let us know and we''ll fix it. <a href="http://{hostname}/#!misc-localorbit_guarantee">Learn more about our guarantee to you</a><br />&nbsp;<br />Your farmers are committed to providing great quality food raised with care, but sometimes problems do happen. If you have an issue with an order, let us know within 24 hours of delivery. We''ll do whatever it takes to make it right.<br />&nbsp;<br />That''s it! So welcome to Local Orbit. And let''s get cooking!<br />&nbsp;<br />Warm wishes,<br />&nbsp;<br />The Local Orbit team<br />&nbsp;<br />','You have the following fields available: {first_name}, {delivery_address}, {hostname}');
	insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:seller_welcome','<h1>Welcome!</h1> Dear {first_name},<br /> <h3>Welcome to a Rewarding Partnership!</h3>  <h4>Getting Started is Simple</h4> <ul> 	<li>Log in to Local Orbit with your email and password.</li> 	<li>Check your profile to make sure everything is correct. Upload a farm photo, add your farm story, or change your password.</li> 	<li>On your dashboard, click on "Create new product". Don''t forget photos!</li> 	<li>All set! Product additions and changes are visible to buyers within seconds.</li> </ul>  The first time you enter inventory it may take you 30 minutes to complete the  session, but we promise that each time it will get faster and faster. And we''re  a cheerful phone call or email away if you need any help. <br />&nbsp;<br /> If you have any questions, please reply to this email or call Customer Service  at 734-418-8628. <br />&nbsp;<br /> <b>Our commitment to you:</b> Local Orbit will be available to you by phone, text,  email and online to provide support. We rarely sleep and will respond quickly to  issues as they come up. If there is a problem with your account, your payments or   anything else, let us know and we''ll fix it.  <a href="{hostname}/#!misc-localorbit_guarantee">Learn more about our guarantee to you</a> <br />&nbsp;<br /> <b>Our commitment to your customers:</b> You provide great quality food raised with care,  but sometimes problems do happen. If a customer has an issue with an order, they''ll  need to let us know within 24 hours of delivery. They then have the right to ask  for a replacement, refund or store credit. <br />&nbsp;<br /> <b>Our terms of service:</b> It''s not nearly as long as the typical prescription medicine  disclaimer and well worth reading.  <a href="{hostname}/#!misc-tos">Read our terms of service here</a> <br />&nbsp;<br /> That''s it! So welcome to Local Orbit. And let''s get selling! <br />&nbsp;<br /> Warm wishes, <br />&nbsp;<br /> The Local Orbit team <br />&nbsp;<br />  ','You have the following fields available: {first_name}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:unit_request','<h1>New unit request</h1>{username} has requested the following new unit:<br />Single: {unitsingle}<br />Plural: {unitplural}<br />&nbsp;<br />They made this request while viewing the following product: <a href="{hostname}/#!products-edit--prod_id-{prod_id}">{prod_name}</a><br />&nbsp;<br /><h2>Additional Note</h2>{notes}','You have the following fields available: {username}, {unitsingle}, {unitplural}, {notes}, {prod_id}, {prod_name}, {hostname}');
insert into phrases (pcat_id,label,default_value,info_note) values (8,'email:product_request','<h1>New product request</h1>{fullname} has requested the following:<br />Product: {product}<br />&nbsp;<br />','You have the following fields available: {fullname}, {product}, {hostname}');

update phrases set edit_type='text';
update phrases set edit_type='rte' where pcat_id=8;


insert into phrases (pcat_id,label,default_value,info_note,edit_type) values (8,'email:buyer_welcome_activated','','You have the following fields available: {hostname}, {first_name}, {delivery_address}, {domain_id}','rte');
insert into phrases (pcat_id,label,default_value,info_note,edit_type) values (8,'email:seller_welcome_activated','','You have the following fields available: {hostname}, {first_name}','rte');

insert into phrases (pcat_id,label,default_value,info_note,edit_type) values (8,'email:org_activated_verified','','You have the following fields available: {hostname}, {first_name}, {delivery_address}, {domain_id}','rte');
insert into phrases (pcat_id,label,default_value,info_note,edit_type) values (8,'email:org_activated_not_verified','','You have the following fields available: {hostname}, {first_name}','rte');
